nelmio_cors:
    paths:
        '^/':
            origin_regex: true
            allow_origin: ['http://localhost:3000']
            allow_headers: ['Content-Type','Authorization']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'PATCH']
            max_age: 3600